[Variables]
;************************************** All ***************************************
defaultFont=ITC Avant Garde Pro XLt
defaultTitleFont=ITC Avant Garde Pro Bk
; Other fonts: Segoe UI, Trebuchet MS
defaultFontSize=9
defaultWidth=190
defaultBoxHeight=14
defaultBarHeight=1
defaultPadding=4

; Colors ***************************************************************

red=204,0,0
darkRed=153,0,0
brightPink=255,0,153
pink=204,102,153
purple=153,0,255

orange=255,102,0
yellow=255,153,0
brightYellow=255,204,0
brightGreen=153,204,0
green=105,155,115

azure=22,193,193,204
brightBlue=51,153,204
blue=0,102,153
mauve=153,153,204
grey=90,106,124

white=255,255,255,200
darkWhite=255,255,255,160

themeColor=#mauve#
themeColorRGB=#mauve#
dividerColor=255,255,255,25
defaultFontColor=#white#
defaultFontColorRGB=255,255,255
defaultHistogramColor=#brightGreen#
fontEffectColor=0,0,0,100

; Strings **************************************************************

openTaskMgr="Open Task Manager"